### ISSUE TITLE
TalonSRX and TalonFX openLoopRamp config effects close looping in velocity

### ISSUE THREAD

**Issue by nimrod46** [CrossTheRoadElec/Phoenix-frc-lib#70] opened 2020-02-24 12:22 UTC
We are using the velocity control mode to control our motor and it seems that defining custom open loop ramp value while having zero in close loop ramp value makes the close loop use the open loop value

We tasted it using TalonSRX and TalonFX, I didn't have much time testing this I just disabled the ramp completely so I don't know what will happened if I define custom value in the close loop value and it's effect if it will be less then the open loop value or if the bug occurs in other close loop modes.

We default all motor using the `configFactoryDefault` method and config it using the `configAllSettings` method.

**Comment by JCaporuscio** [comment] 2020-02-24 21:37
Do you have a set of steps to reliably reproduce the issue you're seeing?
How/what are you measuring that indicates the openLoopRamp setting is improperly affecting closed-loop output?

**Comment by nimrod46** [comment] 2020-02-25 08:53
> Do you have a set of steps to reliably reproduce the issue you're seeing?
> How/what are you measuring that indicates the openLoopRamp setting is improperly affecting closed-loop output?

I don't have access to a robot to test it, you can't reproduce the bug? I used a big ramp to see that it's takes effect, I.e put 10 in the open loop ramp then 0 and saw the difference while close-looping.

**Comment by JCaporuscio** [comment] 2020-02-25 19:34
You have a claim that no one else has reported yet, and a quick sanity check on our end does not reveal the issue you're claiming.

So in order to address the issue we need detailed steps to reproduce the problem.  In general, this is something you should provide whenever reporting an issue (to us or anyone else).

**Comment by nimrod46** [comment] 2020-02-28 13:32
> You have a claim that no one else has reported yet, and a quick sanity check on our end does not reveal the issue you're claiming.
> 
> So in order to address the issue we need detailed steps to reproduce the problem. In general, this is something you should provide whenever reporting an issue (to us or anyone else).

I will make a quick test code and share it once I will be able to test it and make sure it's contains the bug I described.

**Comment by JCaporuscio** [comment] 2021-01-13 21:04
Closing since issue has not been reproduced.
If issue is still current, please e-mail support@ctr-electronics.com or make a new tracker on our releases repo.
https://github.com/CrossTheRoadElec/Phoenix-Releases

**Closed as completed by JCaporuscio** 2021-01-13 21:04 UTC
